version: '3'
services:
  server:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    - ./site:/usr/share/nginx/html
    - ./nginx/nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt # New Line!
    - ./nginx/nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key # New Line!
    ports:
    - "8080:80"
    - "443:443" # Hey docker start listening on 443, and redirect to 443
